# Generated by Django 3.1 on 2020-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
